### ISSUE TITLE
Rule search doesn't end the string match properly, can find trailing characters

### ISSUE THREAD

**Issue by KingSupernova31** [KingSupernova31/RulesGuru#100]
Searching for rule 702.6 will include questions that cite 702.60.

**Comment by draguar** [comment]
Do we agree that the search should include questions citing 702.6a? And that searching for rule 702 should include questions citing 702.6?

**Comment by KingSupernova31** [comment]
If there's no period, yes. A search for `702.6` should include child rules like  702.6a, but a search for `702.6.` should only match that exact rule.
