### ISSUE TITLE
Some searchlinks don't work.

### ISSUE THREAD

**Issue by KingSupernova31** [KingSupernova31/RulesGuru#105]
Like this one.

https://rulesguru.net/?RG1g7hI4lIIGG

**Comment by draguar** [comment]
What are the criteria it is supposed to link to ?

**Comment by KingSupernova31** [comment]
Ah, that seems like important information, whoops. That's the searchLink for fully open settings (returns all finished questions) plus the tag "Rules errors and ambiguities".

`{\"level\":[\"1\",\"2\",\"3\",\"Corner Case\"],\"complexity\":[\"Simple\",\"Intermediate\",\"Complicated\"],\"legality\":\"All of Magic\",\"expansions\":[],\"tags\":[\"Rules errors and ambiguities\"],\"tagsConjunc\":\"AND\",\"rules\":[],\"rulesConjunc\":\"AND\",\"cards\":[],\"cardsConjunc\":\"OR\",\"cardDisplayFormat\":\"Image\",\"playableOnly\":false}"`

**Comment by draguar** [comment]
It seems to simply be a discrepancy between allTags.js and searchLinkMappings.js in public_html/GlobalResources.

allTags contains "Mana value" and "Rules errors and ambiguities" which do not exist in searchLinkMappings.tags

Reciprocally, searchLinkMappings.tags contains "supertypes", "subtypes", "Converted mana cost", "Undefined answers", "Unintended answers", "aura", "counters", "April Fools 2020" which are not in allTags.js, but this should not be a problem as user can not generate searchlinks from these. Note that "subtypes", "aura" and "counters" are duplicates of the same tags starting with an uppercase, which exist in both files ("Supertype" however does not exist).

**Comment by KingSupernova31** [comment]
Ah, I must have screwed that up when I added those two tags manually. I haven't had to do the same thing with rules or card names, so I don't think either of those will have similar bugs. Can you fix the files? You can grab the most recent versions of the files from the live site (I also just added them to the github repo) and edit them as necessary.

The superfluous tags in searchLinkMappings.js shouldn't be an issue, I just didn't bother removing those when we stopped using those tags.
