### ISSUE TITLE
Preview doesn't display for some questions

### ISSUE THREAD

**Issue by KingSupernova31** [KingSupernova31/RulesGuru#106]
Attempting to open the preview on question 793 leads to a bug in the console and the preview not displaying properly.

**Comment by draguar** [comment]
There are no names for [AP1] and [AP2] (2-headed giant). Should we make it so that [AP1] and [AP2] are two names starting with A, but different? Currently, their opponents [NAP1] and [NAP 2] will be named starting with B and C, if I understand the code correctly

**Comment by KingSupernova31** [comment]
`[AP1]` is not valid formatting, it should be `[APa]`. The bug is that the preview is erroring on this invalid formatting for some reason. If you look at question #4000, that also has an invalid expression, but the preview handles it properly.

**Comment by KingSupernova31** [comment]
That seems to have fixed the error, but the validation is still not recognizing that expression as invalid.

**Comment by KingSupernova31** [comment]
Ah, it's because NAP1 is valid, and the regex doesn't distinguish between the two.
