### ISSUE TITLE
Replace deprecated AR API routes

### ISSUE THREAD

**Issue by lunakv** [KingSupernova31/RulesGuru#163]
Some of the API routes on Academy Ruins [have been changed](https://github.com/lunakv/academyruins-api/releases/tag/v0.2.0) (by location only, the actual contents stay the same). Those links should be replaced sometime in the near-ish future.

**Comment by KingSupernova31** [comment]
Thanks for the heads up. They don't seem to be working quite yet; see https://github.com/lunakv/academyruins-api/issues/28.
